import {Inter} from "next/font/google";
import "./globals.css";
//Import react-animated-cursor
import AnimatedCursor from "react-animated-cursor";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimatedCursor
          innerStyle={{
            backgroundColor: "#000",
          }}
          outerStyle={{
            backgroundColor: "rgba(0, 0, 0, 0.2)",
          }}
          clickables={[
            "a",
            "img",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
          ]}
        />
        {children}
      </body>
    </html>
  );
}
