import {Roboto} from "next/font/google";
import "./globals.css";
//Import react-animated-cursor
import AnimatedCursor from "react-animated-cursor";
import {Weight} from "lucide-react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <AnimatedCursor
          innerStyle={{
            backgroundColor: "#000",
          }}
          outerStyle={{
            backgroundColor: "rgba(0, 0, 0, 0.2)",
          }}
          clickables={[
            "a",
            "img",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
          ]}
        />
        {children}
      </body>
    </html>
  );
}
