import {Inter} from "next/font/google";
import "./globals.css";
//Import own components
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";
//Import react-animated-cursor
import AnimatedCursor from "react-animated-cursor";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimatedCursor
          innerStyle={{
            backgroundColor: "#000",
          }}
          outerStyle={{
            backgroundColor: "rgba(0, 0, 0, 0.2)",
          }}
        />
        <div className="container">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
